[build]
  command = "pnpm run build"
  publish = ".next"

[build.environment]
  # Esto le dice a Netlify que instale pnpm antes de empezar
  NPM_FLAGS = "--version" 
  PNPM_FLAGS = "--frozen-lockfile"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["next.config.js"]
  external_node_modules = ["firebase"]